### ISSUE TITLE
support namespace

### ISSUE THREAD

**Issue by pr8kerl** [alam0rt/parameter-store-generator#3]
The plugin seems to assume the namespace is set correctly in the kube client context.
This is not always the case. If I explicitly set the namespace in the ParameterStore manifest, the resulting secret does not use it.

**Comment by alam0rt** [comment]
hey @pr8kerl, I have fixed this. The solution was to leverage the existing `metav1.ObjectMeta` type instead of re implementing it myself.
 
https://github.com/alam0rt/kustomize-aws-ssm-generator/pull/4
